config/routes.rb
GHGSuite::Application.routes.draw do

  match "login" => 'user_sessions#new', :as => :login
  resources :users
  resource  :user_session

  match "feedback" => 'application#feedback', :as => :feedback
  match "report" => 'calculation#report', :as => :report
  match "calculation/update" => 'calculation#update', :as => :update
  match "calculation/:row/delete" => 'calculation#delete', :as => :delete
  match "calculation/:type/add" => 'calculation#add', :as => :add
  match "calculation/:type/sort" => 'calculation#sort', :as => :sort
  match "calculation/:type/toggle_optional" => 'calculation#toggle_optional', :as => :toggle_optional
  match "calculation/:type" => 'calculation#calculation', :as => :calculation
  match "summary" => 'calculation#summary', :as => :summary
  match "summary/update" => 'calculation#update_summary', :as => :update_summary
  match "help" => 'application#help', :as => :help
  root :to => 'application#home'

end

app/controllers/calculation_controller.rb
# Copyright (C) 2008-2012 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

class CalculationController < ApplicationController

  helper CalculationHelper

  before_filter :login_required
  before_filter :initialize_prototype_calculations
  helper_method :output_terms_in_order, :calculation_terms_in_table_order

  MINIMUM_TABLE_SIZE_IN_ROWS = 7

  @@calculation_set = AMEE::DataAbstraction::CalculationSet.find($sheet)

  def summary
    generate_summary_data
  end

  def report
    generate_summary_data
    render 'report', :layout => 'report'
  end
  
  def calculation
    type = params[:type].to_sym

    unless defined?(session[type][:show_optional])
      session[type] = { :show_optional => false }
    end

    @calculations          = find_calculations_by_type(type, :minimum => MINIMUM_TABLE_SIZE_IN_ROWS) and convert_outputs(@calculations)
    @prototype_calculation = @prototype_calculations[type]
    @title                 = @prototype_calculation.name

    render '_calculation'
  end

  def add
    @calculation = initialize_calculation(params[:type])
    @calculation.outputs.each do |output|
      @calculation.contents[output.label.to_sym] = output.convert_unit(:unit => current_user.return_unit)
    end
  end

  def delete
    if @calculation = find_calculation_by_id(params[:id])
      @calculation.delete
    end
    @row_id = params[:row]
    @calculations = find_calculations_by_type(@calculation.label)
    convert_outputs(@calculations)

    @prototype_calculation = @prototype_calculations[@calculation.label]
  end

  def update
    if id = params['id']
      @calculation = find_calculation_by_id(id)
    else
      @calculation = initialize_calculation(params['type'])
    end
    unless @calculation.choose({ params['path'] => { params['attribute'] => params['data']}} )
      @calculation.clear_invalid_terms!
      @calculation.autodrill
    end
    @calculation.calculate!
    @calculation.save
    @calculations = find_calculations_by_type(@calculation.label)
    @calculation.outputs.each do |output|
      @calculation.contents[output.label.to_sym] = output.convert_unit(:unit => current_user.return_unit)
    end
    convert_outputs(@calculations)
    @prototype_calculation = @prototype_calculations[@calculation.label]
    @row_id = params['row']

    if params['id'].nil? || (@calculation[params['path'].to_sym].is_a? AMEE::DataAbstraction::Drill)
      render 'update_row.js'
    else
      render 'update_results.js'
    end
  end

  def toggle_optional
    type = params[:type].to_sym
    
    if params[:show_optional] == 'true'
      session[type] = { :show_optional => true }
    end
    if params[:show_optional] == 'false'
      session[type] = { :show_optional => false }
    end

    @calculations          = find_calculations_by_type(type, :minimum => MINIMUM_TABLE_SIZE_IN_ROWS) and convert_outputs(@calculations)
    @prototype_calculation = @prototype_calculations[type]
    @title                 = @prototype_calculation.name

    render 'update.js'
  end

  def sort
    type = params[:type].to_sym

    @calculations          = find_calculations_by_type(type) and convert_outputs(@calculations)
    @prototype_calculation = @prototype_calculations[type]
    @title                 = @prototype_calculation.name

    @calculations = @calculations.sort_by!(params[:ascending].to_sym) if params[:ascending]
    @calculations = @calculations.sort_by!(params[:descending].to_sym).reverse! if params[:descending]

    if @calculations.size < MINIMUM_TABLE_SIZE_IN_ROWS
      (MINIMUM_TABLE_SIZE_IN_ROWS - @calculations.size).times do
        @calculations << initialize_calculation(type)
      end
    end

    render 'update.js'
  end

  protected

  def self.calculation_set
    class_variable_get("@@calculation_set")
  end

  def calculation_set
    CalculationController.calculation_set
  end

  # Find a specific calcualtion on the basis of it's database reference
  def find_calculation_by_id(id)
    AMEE::DataAbstraction::OngoingCalculation.find(id.to_i, :include => 'terms')
  end

  # Find all stored calculations for a particular calculation type. First
  # argument must represent the label (string or symbol) of the calcualtion
  # type. Two other options can be specified as a hash.
  #
  # :minimum => <an integer> #=> Returns the specified minumim number
  # of calculations. If the number of
  # retrieved calculations is smaller
  # than the minimum, the number is made
  # up by initializing blank calculations
  #
  # :calculation_set => <instance of AMEE::DataAbstraction::CalculationSet>
  #
  # #=> Specifies the calculation set within
  # which to find the calculation type
  # required. This is only required if
  # a minimum requirement is specified
  # AND the calculation set is NOT declared
  # at the controller level (see the
  # controller class methods, above).
  #
  #
  def find_calculations_by_type(label,options={})
    collection = AMEE::DataAbstraction::OngoingCalculation.find_by_type(:all, label.to_s, :include => 'terms')
    if options[:minimum] and collection.size < options[:minimum]
      (options[:minimum] - collection.size).times do
        collection << initialize_calculation(label)
      end
    end
    return collection
  end

  # Initialize a new calculation of a type specified by the first argument.
  # This argument should represent the label of the prototype caluclation
  # required. The calculation set within which the prototype calculation can
  # be found should be passed as a second argument unless this is defined at
  # the controller level (see controller class methods, above).
  #
  def initialize_calculation(label)
    label = label.to_sym unless label.is_a? Symbol
    if calculation_set
      calculation_set[label].begin_calculation
    else
      raise ArgumentError, "CalculationSet for controller not defined. Must specify at controller level or provide as second argument."
    end
  end

  def initialize_prototype_calculations
    @calculation_set        = calculation_set
    @prototype_calculations = @calculation_set.calculations
  end

  def prototype_outputs_in_order
    prototype_outputs = AMEE::DataAbstraction::CalculationCollection.new(@prototype_calculations.values).terms.outputs.visible.first_of_each_type
    prototype_outputs << AMEE::DataAbstraction::Output.new {label :co2e; name 'CO2e'} unless prototype_outputs.any? {|output| output.label == :co2e}
    output_terms_in_order(prototype_outputs)
  end

  def calculation_terms_in_table_order(calculation,include_optional=false,include_outputs=true)
    terms  = []
    terms  = terms + calculation.metadata.visible
    terms += calculation.drills.visible
    terms += calculation.profiles.compulsory.visible
    terms += calculation.profiles.optional.visible if include_optional
    terms += output_terms_in_order(calculation.outputs.visible) if include_outputs
    return terms
  end

  def output_terms_in_order(outputs)
    outputs.sort! {|output,next_output| output.label.to_s <=> next_output.label.to_s}
    outputs.move_by(:label,:co2,0)
    outputs.move_by(:label,:co2e,0) and outputs.rotate
    return outputs
  end

  def convert_outputs(collection)
    return collection if current_user.return_unit == 'kg' || collection.empty?
    outputs = [collection.outputs.visible.first_of_each_type.labels].flatten
    outputs.each do |output|
      collection.standardize_units!(output.to_sym, current_user.return_unit) if collection.respond_to?(output.to_sym)
    end
  end

  def generate_summary_data
    @prototype_outputs = prototype_outputs_in_order
    @headers           = @prototype_outputs.map { |output| output.name }.unshift("Calculation methodology")
    @table             = ghg_totals_by_calculation(@prototype_outputs)
    @all_calculations  = @calculation_set.all_ongoing_calculations
    @totals            = ghg_totals(@all_calculations,@prototype_outputs)
  end

  def ghg_totals_by_calculation(outputs)
    totals = @prototype_calculations.map do |label,calc|
      calcs = AMEE::DataAbstraction::OngoingCalculation.find_by_type(:all, label.to_s, :include => 'terms')
      array = [calc]
      if calcs.empty?
        (outputs.size).times { array << nil }
      else
        convert_outputs(calcs)
        outputs.each do |ghg|
          if ghg.label == :co2e
            array << calcs.co2_or_co2e_outputs.sum
          else
            array << (calc[ghg.label] ? calcs.send(ghg.label).sum : nil)
          end
        end
      end
      array
    end
    return totals
  end

  def ghg_totals(calculations,outputs)
    convert_outputs(calculations)
    totals = AMEE::DataAbstraction::TermsList.new
    outputs.each do |output|
      next if output.label == :co2e
      if calculations.respond_to?(output.label)
        totals << calculations.send(output.label).sum
      else
        totals << AMEE::Analytics::Result.new { name output.name; label output.label; value 0.0}
      end
    end
    totals << co2e_sum = calculations.co2_or_co2e_outputs.sum and co2e_sum.label(:co2e) and co2e_sum.name('CO2e')
    return totals
  end

end

app/helpers/calculation_helper.rb
# Copyright (C) 2008-2012 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

module CalculationHelper

  # Generate an element rendering a single term. By default, this element
  # represents the term value, wrapped within <span> tags. In cases where units or
  # per units are involved, these are appended within successive <span> tags.
  #
  # By default, each element is wrapped within <span> tags.
  #
  # A number of options are supported:
  #
  # :tag => <some tag, e.g. 'td'> - Wraps each element within alternative html tags within tables.
  #
  # :unit_format => <symbol> - Set the format for describing units. Valid
  # values include :name, :pluralized_name,
  # :symbol and :label
  #
  # :decimal_places - Set the decimal places of any numeric value
  #
  # :per_unit_delimiter - Set the character or string used to delimit
  # units and per unit, Defaults to "/"
  #
  def show_term_tag(term,options={})
    options[:unit_format] ||= :symbol
    options[:term] = term
    options[:tag] ||= 'span'
    options[:per_unit_delimiter] ||= '/'
    options[:decimal_places] ||= nil
    options[:format_number] ||= false
    options[:delimiter] ||= nil
    options[:separator] ||= nil
    render 'calculation/show_term', options
  end

  # Generate a form input field (text field) for a term attribute. The second argument
  # represents a hash of options which can be optionally used to specify the term
  # attribute to be used and the size of the text field. Valid option keys are:
  #
  # :attribute - the label of the term attribute, e.g. :value, :unit
  # :size - size, in pixels, of the text field
  #
  # If no term attribute is explcitly specified, it is assume that the text field
  # represents the term 'value' attribute. Default text field size is 10 pixels.
  #
  def term_input_tag(term,options={})
    options[:size] ||= 10
    options[:disabled] = term.disabled?
    options[:class] = html_class_for_term(term,:value)
    text_field_tag options[:name], term.value, options
  end

  # Generate a select list containing the valid choices for a term value
  def term_choices_select_tag(term,options={})
    choices = term.options_for_select
    selected = (term.set? ? term.value : nil)
    options[:disabled] ||= term.disabled?
    options[:class] = html_class_for_term(term,:value)
    select_tag options[:name], options_for_select(choices, selected), options
  end

  # Generate a select list containing the valid alternatives for a term per unit.
  #
  # Specify the format for list entries as an optional key (:format) within the
  # options hash, i.e. the format in which the unit is described. Valid options
  # include:
  #
  # :name
  # :pluralized_name
  # :symbol
  # :label
  #
  # Defaults to :symbol if not explcitly specified
  #
  # This method generates default html classes for the select element, based
  # on the #html_class_for_term method.
  #
  # If options[:parent] is provided, this will be used as the parent key for the
  # selected value within the params hash, e.g.
  #
  # term_unit_select_tag(term,options[:parent]=>'mass') #=>
  #
  # <select class="profile aluminium_quantity unit" id="mass_unit" name="mass[unit]">
  # <option value="g">g</option>
  # <option value="ton_uk">ton</option>
  # ...
  # </select>
  #
  def term_unit_select_tag(term,options={})
    raise if options[:format] and not [:name,:pluralized_name,:symbol,:label].include? options[:format]
    format = options.delete(:format) || :symbol
    parent = options.delete(:parent) || nil
    options[:class] = html_class_for_term(term,:unit)
    collection_select parent,:unit,term.unit_choices,:label,format,
                    {:selected => term.unit.label},options
  end

  # Generate a select list containing the valid alternatives for a term per unit.
  #
  # Specify the format for list entries as an optional key (:format) within the
  # options hash, i.e. the format in which the unit is described. Valid options
  # are as above. Defaults to :symbol if not explcitly specified.
  #
  # This method generates default html classes for the select element, based
  # on the #html_class_for_term method.
  #
  # # If options[:parent] is provided, this will be used as the parent key for the
  # selected value within the params hash. See above.
  #
  def term_per_unit_select_tag(term,options={})
    raise if options[:format] and not [:name,:pluralized_name,:symbol,:label].include? options[:format]
    format = options.delete(:format) || :symbol
    parent = options.delete(:parent) || nil
    options[:class] = html_class_for_term(term,:per_unit)
    collection_select parent,:per_unit,term.per_unit_choices,:label,format,
                    {:selected => term.per_unit.label},options
  end

  # Return a term value rounded to the specified number of decimal places.
  # If the term value is not numeric, then the term value is simply returned.
  # This allows rounding to be applied systematically across caluclations and
  # terms without breaking.
  #
  def rounded_term_value(term, decimal_places)
    if term.has_numeric_value? && decimal_places
      return term.value.round(decimal_places)
    else
      return term.value
    end
  end

  # Generate a string providing some default html class for a term representation.
  # Requires the term to be provided as a first argument, and a reference to the
  # term attribute under consideration as the second argument, e.g.
  #
  # html_class_for_term(obj,:unit) #=> "profile mass unit"
  #
  # html_class_for_term(obj,:value) #=> "drill type value"
  #
  # The attribute can be provided as a string or a symbol
  #
  def html_class_for_term(term,attr)
    "amee-#{term_class_string(term)} calc-#{term.label} term-#{attr.to_s}"
  end

  protected

  # Parse the class name from the full namespace - used to provide
  # default html classes for term views
  def term_class_string(term)
    return term.class.to_s.split("::").last.downcase
  end
end

app/views/calculation/_calculation.html.erb
<%= render :partial => 'calculation_scripts' %>
<%= render :partial => 'help' %>
<span class="ajaxloader" style="display:none;"><%= image_tag 'loading_small.gif' %></span>
<div id="calculation_page" class="content_pane">
  <div id="generic-loading"></div>
  <div id="amee-strap" class="calculation">
    <%= image_tag 'AMEE-Logo2011-LINE_Green-small.png', :alt => 'AMEE: Environment Intelligence. Everywhere' %>
  </div>
  <% optional = session[@prototype_calculation.label][:show_optional] %>
  <div class="links">
    <% if optional %>
      <div class="link" id="toggle-optional">
        <%= link_to 'Show compulsory inputs only', toggle_optional_path(:type => @prototype_calculation.label,
                                                                        :show_optional => 'false'),
                                                   :remote => true %>
      </div>
    <% else %>
      <div class="link" id="toggle-optional">
      <%= link_to 'Show optional inputs', toggle_optional_path(:type => @prototype_calculation.label,
                                                               :show_optional => 'true'),
                                          :remote => true %>
      </div>
    <% end %>
    <div id="guide-switch" class="link">
      <%= "Show guide" %>
    </div>
  </div>
  <br />
  <div id="table_container">
    <table id="calculation_table">
      <tr>
        <% up_image = image_tag "up-arrow.png", :alt => 'u' %>
        <% down_image = image_tag "down-arrow.png", :alt => 'd' %>
        <% calculation_terms_in_table_order(@prototype_calculation,optional).each do |term| %>
          <th>
            <span class="column-header"><%=  term.name %></span>
            <span class="sort-buttons">
              <%=link_to up_image, sort_path(:type => @prototype_calculation.label,
                                             :ascending => term.label),
                                   :remote => true %>
              <%=link_to down_image, sort_path(:type => @prototype_calculation.label,
                                               :descending => term.label),
                                     :remote => true %>
            </span>
          </th>
        <%end%>
        <th class="delete"></th>
      </tr>
      <% @calculations.each do |calc| %>
        <%= render 'edit_row', :calculation=>calc, :optional => optional %>
      <%end%>
      <tr id="totals">
        <%= render("total_row", :calculations => @calculations, :prototype_calculation => @prototype_calculation, :optional => optional) unless @calculations.empty? %>
      </tr>
    </table>
    <div style="clear: both;"></div>
  </div>
  <div id="table-base-nav">
    <span id="add-calc">
      <% image = image_tag "add_calc.png", :alt => 'Add a calculation' %>
      <%= link_to raw("Add a calculation"+image), add_path(:type => @prototype_calculation.label),
                                                  :remote => true %>
    </span>
    <span id="summary-link">
      <% image = image_tag "go_to_summary.png", :alt => 'Go to summary' %>
      <%= link_to raw("Go to summary page"+image), summary_path %>
    </span>
  </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />

app/views/calculation/_edit_row.html.erb
<% row_id = "row-#{rand(1e8)}" %>
<% ref = ( calculation.id ? "calc_db_id='#{calculation.id}'" : "calc_type='#{calculation.label}'" ) %>
<tr id="<%= row_id%>" <%= ref %>>
<% optional = session[calculation.label.to_s][:show_optional] %>
<% calculation_terms_in_table_order(calculation,optional,false).each do |term|%>
  <td class="<%= html_class_for_term(term,:edit)%>">
    <%= render 'edit_term', :term => term %>
  </td>
<% end %>
<% unless calculation.outputs.visible.empty? %>
  <% output_terms_in_order(calculation.outputs.visible).each do |term|%>
    <td id="<%= "#{row_id}-#{term.label}" %>" class="<%= html_class_for_term(term,:show)%>">
      <%= show_term_tag(term,:decimal_places => 2, :format_number => true, :delimiter => " ") %>
    </td>
  <%end%>
<% else %>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
<% end %>
<% delete_symbol = image_tag "delete.png", :alt => 'Delete' %>
<td class="delete">
  <%= link_to delete_symbol, delete_path(:id => calculation.id, :row => row_id), :class => "delete-link", :remote => true %>
</td>
</tr>

app/views/calculation/_edit_term.html.erb
<% if term.drop_down? %>
  <%= term_choices_select_tag(term) %>
<%else%>
  <%= term_input_tag(term) %>
  <% unless term.default_unit.nil? %>
    <%= term_unit_select_tag(term) %>
  <% end %>
  <% unless term.default_per_unit.nil? %>
    <%= "/" %>
    <%= term_per_unit_select_tag(term) %>
  <% end %>
<%end%>

app/views/calculation/_help.html.erb
<% optional = session[@prototype_calculation.label][:show_optional] %>
<div id="guide_container" style="display:none">
  <%= image_tag "close_guide.png", :alt => 'Close guide', :id => "close-guide" %>
  <div id="help_container">
    <div id="help">
      <div class="note head">
        <h3 class="note"><%= @prototype_calculation.name %></h3>
        <p class="note"><%= @prototype_calculation[:note] %></p>
        <p class="note">See below for information on each methodology component...</p>
      </div>
      <% calculation_terms_in_table_order(@prototype_calculation,optional).each do |term| %>
        <div class="note">
          <h3 class="note"><%= term.name %></h3>
          <p class="note"><%= term.note %></p>
        </div>
      <%end%>
      <div class="note base">
        <span id="discover-link">
          <h3 class="note" data="<%= @prototype_calculation.discover_url %>">
            See this methodology in AMEEdiscover >>
          </h3>
        </span>
        <span id="discover-logo">
          <%= image_tag "AMEE_bug_34x36.png", :alt => 'AMEEdiscover' %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/calculation/_show_term.html.erb
<% value = rounded_term_value(term,decimal_places) %>
<% if format_number && term.has_numeric_value? %>
  <% options = {} %>
  <% options[:delimiter] = delimiter if delimiter %>
  <% options[:separator] = separator if separator %>
  <% value = number_with_delimiter(value, options) %>
<% end %>
<%= content_tag tag.to_sym, value, :class => html_class_for_term(term, :value) %>
<% unless term.unit.nil? %>
  <%= content_tag tag.to_sym, term.unit.send(unit_format), :class => html_class_for_term(term, :unit) %>
<% else %>
  <%= content_tag tag.to_sym, nil, :class => html_class_for_term(term, :unit) %>
<% end %>
<% unless term.per_unit.nil? %>
  <%= content_tag tag.to_sym, per_unit_delimiter, :class => html_class_for_term(term, :per_unit_delimiter) %>
  <%= content_tag tag.to_sym, term.per_unit.send(unit_format), :class => html_class_for_term(term, :per_unit) %>
<% else %>
  <%= content_tag tag.to_sym, nil, :class => html_class_for_term(term, :per_unit_delimiter) %>
  <%= content_tag tag.to_sym, nil, :class => html_class_for_term(term, :per_unit) %>
<% end %>

app/views/calculation/_tab_scripts.html.erb
<%= javascript_tag do %>

  $(document).ready(function(){

    $(window).resize(function(){
      centreTabs();
    });

    stackTabs();

    // make selected tab more prominent
    $("#calculation_tabs .selected").each(function() {
      var currentHeight = $(this).height();
      var newHeight = currentHeight + 10;
      $(this).height(newHeight);
    });

    // Show fully opaque tabs on hover
    $("#calculation_tabs .tabs").live('mouseenter',function(){
      $("#tab-wrapper").removeClass('tab-opacity');
    }).live('mouseleave',function(){
      $("#tab-wrapper").addClass('tab-opacity');
    });

    unselectedTabs = $("#calculation_tabs .tab").filter(function(){
      return !$(this).hasClass('selected');
    });

    // Make tabs grow on hover
    unselectedTabs.bind('mouseenter',function() {
      currentHeight = $(this).height();
      newHeight = currentHeight + 10;
      $(this).height(newHeight);
    });

    // Make tabs shrink on hover end
    unselectedTabs.bind('mouseleave',function() {
      currentHeight = $(this).height();
      newHeight = currentHeight - 10;
      $(this).height(newHeight);
    });

  });

  // tab row padding gives some flexibility to the tab stacking algorithm by
  // providing some extra room within which to organise tabs into appropriately
  // sized rows
  var tabRowPadding = 100;
  var tabPaddingAndMargin = 22;

  function getCumulativeWidth(array) {
    width = 0;
    for (i=0; i<array.length; i++) {
      width = width + $(array[i]).width()+tabPaddingAndMargin;
    }
    return width;
  };

  // Returns the current window width, minus some padding space
  function windowWidthForTabs() {
    windowWidth = $(window).width();
    if (windowWidth < 1000) {
      windowWidth = 1000;
    }
    windowWidth -= tabRowPadding;
    return windowWidth;
  }

  function centreTabs() {
    windowWidth = windowWidthForTabs();
    $('.tabs').each(function() {
      $(this).css('left', ((windowWidth-$(this).width())/2)+tabRowPadding/2);
    });
  }

  function stackTabs() {

    windowWidth = windowWidthForTabs();
    tabs = $("div#tab-wrapper div.tabs .tab");

    tabCount = tabs.length;
    totalTabWidth = getCumulativeWidth(tabs);
    numberOfRows = Math.ceil(totalTabWidth/windowWidth);
    maxRowWidth = (totalTabWidth/numberOfRows);

    // Allow some flexibility around row width if max width does not exceed
    // padded window width
    if ((maxRowWidth) < windowWidth){
      maxRowWidth += tabRowPadding;
    }

    // Keep track of which tab algorithm is up to
    cumulativeTabIndex = 0;

    for (r = 0;r <= numberOfRows; r++) {
      tabIndex = cumulativeTabIndex;
      cumulativeWidth = 0;
      while (cumulativeWidth < maxRowWidth){
        if (tabIndex-1 > tabCount) {
          break;
        } else if (tabIndex-1 == tabCount) {
          row = tabs.slice(cumulativeTabIndex,tabIndex);
        } else {
          // Find cumulative width using next tab for next iteration
          row = tabs.slice(cumulativeTabIndex,tabIndex+1);
          cumulativeWidth = getCumulativeWidth(row);

          // Make row contain only tabs which have had width compared so far
          if (row.length > 0){
            row = row.slice(0,-1);
          }
        }
        tabIndex = tabIndex+1;
      }

      $(row).filter($('.tab')).each(function(){
        currentHeight = $(this).height();
        $(this).height(currentHeight + (30 * r));
      });

      newRow = $(document.createElement("div")).addClass('tabs').append(row);
      $('#tab-wrapper').append(newRow);

      cumulativeTabIndex = tabIndex-1;
    }

    // Remove original tab container
    $('#calculation_tabs #original-tabs').remove();

    // Add the appropriate z-indices to each row
    z=1;
    $($('#calculation_tabs .tabs').get().reverse()).each(function(){
      $(this).css('z-index', z);
      z=z+1;
    });
    
    centreTabs();
  }

<% end %>

app/views/calculation/_tabs.html.erb
<div id="tab-wrapper" class="tab-opacity">
  <div id="original-tabs" class="tabs">
    <div class="tab<%= ' selected' if request.fullpath == '/summary' %>" id="summary_tab">
      <%= link_to 'Summary', summary_path %>
    </div>
    <% prototype_calculations.each do |label,calc| %>
      <div class="tab<%= ' selected' if prototype_calculation && prototype_calculation.label == label %>" id="<%= "#{label}_tab" %>">
        <%= link_to calc.name, calculation_path(:type => label)  %>
      </div>
    <% end %>
  </div>
</div>

app/views/calculation/_total_row.html.erb
<% optional = session[prototype_calculation.label][:show_optional] %>
<% calculation_terms_in_table_order(prototype_calculation,optional,false).each do |term|%>
  <td></td>
<% end %>
<% output_terms_in_order(prototype_calculation.outputs.visible).each do |term| %>
  <% if calculations.respond_to?(term.label) %>
    <% result = calculations.send(term.label).sum(current_user.return_unit) rescue nil %>
    <td class="amee-result <%= "calc-#{term.label}" %>"><%= show_term_tag(result,:decimal_places => 2, :format_number => true, :delimiter => " ") %></td>
  <% else %>
    <td class="amee-result <%= "calc-#{term.label}" %>"><%= "0.0" %></td>
  <% end %>
<% end %>
<td class="delete"></td>

app/views/calculation/update.js.erb
$('#contentarea').html('<%= escape_javascript(render :partial => "calculation") %>');
setTableContainerWidths();

app/views/calculation/update_row.js.erb
$('#<%= @row_id %>').replaceWith('<%= escape_javascript(render :partial => 'edit_row', :locals => { :calculation => @calculation }) %>');
$('#totals').html('<%= escape_javascript(render :partial => 'total_row', :locals => { :calculations => @calculations, :prototype_calculation => @prototype_calculation }) %>');
setTableContainerWidths();