config/routes.rb
GHGSuite::Application.routes.draw do

  match "login" => 'user_sessions#new', :as => :login
  resources :users
  resource  :user_session

  match "feedback" => 'application#feedback', :as => :feedback
  match "report" => 'calculation#report', :as => :report
  match "calculation/update" => 'calculation#update', :as => :update
  match "calculation/:row/delete" => 'calculation#delete', :as => :delete
  match "calculation/:type/add" => 'calculation#add', :as => :add
  match "calculation/:type/sort" => 'calculation#sort', :as => :sort
  match "calculation/:type/toggle_optional" => 'calculation#toggle_optional', :as => :toggle_optional
  match "calculation/:type" => 'calculation#calculation', :as => :calculation
  match "summary" => 'calculation#summary', :as => :summary
  match "summary/update" => 'calculation#update_summary', :as => :update_summary
  match "help" => 'application#help', :as => :help
  root :to => 'application#home'

end

app/views/layouts/_demo_banner.html.erb
<div id="demo-banner">
  This is a demo version. For more details
  <%= link_to 'contact us', "http://www.amee.com/homepage/contact-us/" %>
  >>
</div>

app/views/layouts/_footer.erb
  <div class="clear"></div>
</div>
<% if @prototype_calculations %>
  <br />
  <br />
  <div id="calculation_tabs">
    <%= render 'calculation/tabs', :prototype_calculations => @prototype_calculations, :prototype_calculation => @prototype_calculation %>
  </div>
<% end %>

app/views/layouts/_header.erb
<div id="header">
  <% if @demo %>
    <%= render :partial => "layouts/demo_banner" %>
  <% end %>
  <div id="header_tabs">
    <% if logged_in? %>
      <% if current_user.is_admin? %>
        <div class="tab">
          <%= link_to 'Admin', users_path %>
        </div>
        <div class="tab">
          <%= link_to 'Settings', edit_user_path(current_user.id) %>
        </div>
      <% end %>
      <div class="tab">
        <%= link_to "Summary", summary_path %>
      </div>
      <div class="tab">
        <%= link_to "Help", help_path %>
      </div>
      <div class="tab">
        <%= link_to 'Send feedback', feedback_path %>
      </div>
      <div class="tab">
        <%= link_to 'Logout', user_session_path(current_user_session.id), :method => 'delete' %>
      </div>
    <% end %>
  </div>
</div>
<div id="contentarea">

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>GHG calculation tool for <%= $tool_name %></title>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'rails' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <%= render :partial => "calculation/tab_scripts" %>
    <%= yield :js %>
    <%= stylesheet_link_tag 'main' %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-24479591-3']);
      _gaq.push(['_trackPageview']);
      (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })();
    </script>
  </head>
  <body>
    <%= render :partial => "layouts/header" %>
    <%= yield %>
    <%= render :partial => "layouts/footer" %>  
  </body>
</html>

app/views/layouts/feedback.html.erb
<div id="feedback">
  <div class="content_pane">
    <h1>We are always trying to find ways to improve our products</h1>
    <h3>Please enter your idea, question or comment below</h3>
    <div id="feedback-form-wrapper">
      <script type="text/javascript" charset="utf-8">
        var is_ssl = ("https:" == document.location.protocol);
        var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
        document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
      </script>

      <script type="text/javascript" charset="utf-8">
        var feedback_widget_options = {};
        feedback_widget_options.display = "inline";
        feedback_widget_options.company = "amee";
        feedback_widget_options.style = "question";
        var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
      </script>

      <script type="text/javascript" charset="utf-8">
        $('iframe').height(400);
      </script>
    </div>
  </div>
  <div id="amee-strap-big">
    <%= image_tag 'AMEE-Logo2011-LINE_Green.png', :alt => 'AMEE: Environment Intelligence. Everywhere' %>
  </div>
</div>

app/views/layouts/help.html.erb
<div id="help-page">
  <div class="content_pane">
    <h3>Welcome to the GHG calculation tool for <%= $tool_name %></h3>
    <div id="instructions">
      <h2 class="instructions">Getting started...</h2>
      <h3 class="instructions">1. Select a process from the tabs at the foot of the page. Each tab corresponds to a method for calculating the emissions associated with a specific activity.</h3>
      <h3 class="instructions">2. The optional input fields which allow you to customise the calculations are hidden by default so you can click 'Show optional inputs' to make all fields available.</h3>
      <h3 class="instructions">3. A guide to the contents and calculations on each tab can be opened by clicking the 'Guide' tab, just above the table.</h3>
      <h3 class="instructions">4. Make calculations by entering data into each table row.</h3>
      <h3 class="instructions">5. You can add associated details (e.g. reporting period, process descriptors) to calculations to match your internal references.</h3>
      <h3 class="instructions">6. If you need more calculations click 'Add a row' to expand the table</h3>
      <h3 class="instructions">7. You can review the total results using the 'Summary' tab</h3>
      <h3 class="instructions">8. On the summary tab you can click the Export to PDF tab above the table to download a report  that you can share.</h3>
      <h2 class="instructions">Adding additional users...</h2>
      <h3 class="instructions">1. To add another user to the app, admin users can go to the Admin page via the link in the top right hand corner of the screen and click to 'Add a new user'.</h3>
      <h3 class="instructions">2. Enter the users email and select a password for them.  Once set up you need to share these with the user and give them the link to sign in. They can reset their password in the 'Settings' page once they sign in for the first time.</h3>
      <h3 class="instructions">3. You choose to make a new user a 'Standard' or 'Admin' user by selecting the Admin tickbox.  Both types of users can edit the data in the app, but only admin users can add new users.</h3>
      <h2 class="instructions">Support / Feedback</h2>
      <h3 class="instructions">If you need help using the app or have feedback about how it could be improved, please submit your question or feedback on the ‘Feedback’ page.  This is available in the top right hand corner of the screen.</h3>
    </div>
  </div>
  <div id="amee-strap-big">
    <%= image_tag 'AMEE-Logo2011-LINE_Green.png', :alt => 'AMEE: Environment Intelligence. Everywhere' %>
  </div>
</div>

app/views/layouts/report.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <%= stylesheet_link_tag 'print', :media => 'print' %>
  </head>
  <body>
    <%= yield %>
  </body>

</html>